### ISSUE TITLE
NPM Test failure - Missing SQLITE3

### ISSUE THREAD

**Issue by Tzuridis** [smubbs/capstone-project-2-expresso#2]
After cloning your repo and installing all the node packages, I am unable to complete the test for your framework. You have to ensure that when someone else downloads your project they are able to run the repo correctly, the error message received states that the node module sqlite3 is missing as that was not installed. I looked in your package.json and did, in fact, see it is not listed under the dependencies.

![image](https://user-images.githubusercontent.com/19315896/42291940-f4909e12-7f9c-11e8-8517-713613b0be1c.png)

**Comment by smubbs** [comment]
Fair call, this appears to be an issue with the files I pushed to the git. The dependencies obviously show sqlite3 in my copy, but didn’t seem to appear in the github version.

Thanks for pointing it out!
