### ISSUE TITLE
Summary - Almost Meets Expectations

### ISSUE THREAD

**Issue by Tzuridis** [smubbs/capstone-project-2-expresso#6]
Overall, a good job with this project. All of your tests pass but I had to do some extra work to get the repo up and running.

Your code files were well formatted and leveraged some great things such as string interpolation to keep your code clean and concise. Your SQL queries were also well-built. SQL can be hard to get right in some cases, but here you seemed to have no problem at all.

As far as improvements go, I would recommend going back through and adding comments to your handler functions and of course adding sqlite3 to the dependencies list. I would also recommend going back through and separating out your queries into variables from their current position as inline arguments to the db module methods. This way you can format your queries in a more readable format.

Barring those minor improvements, really good job with this. Keep up the good work!

**Comment by smubbs** [comment]
Thanks for the thorough and thoughtful feedback on this project. Some really good points here that I will take on board.
